repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--line-length", "100"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--max-line-length", "100", "--ignore=E203,W503"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies: ["tomli"]
        args: ["--ignore-words=doc/accept.txt"]

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.3.0
#    hooks:
#    -   id: mypy
#        exclude: "tests/|doc/|src/heresycardbuilder/media/|src/heresycardbuilder/spellchecker/"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: trailing-whitespace
    - id: check-added-large-files
      exclude: "src/heresycardbuilder/media/|src/heresycardbuilder/spellchecker/"
    - id: check-case-conflict