name: HeresyCardBuilder

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install .[dev]
        pip install .[tests]
    - name: Pre-commit
      run: |
        pre-commit run --all-files
    - name: build
      run: |
        python -m build
    - name: Test with pytest
      run: |
        pytest
